name: OmegaSMPlugin
version: '${project.version}'
main: com.notverygoodatthis.omegasmplugin.OmegaSMPlugin
api-version: 1.19
authors: [ NotVeryGoodAtThis ]
description: The official Omega SMP plugin

commands:
  omegarevive:
    description: Revive a banned player using a revival item
    usage: /<command>

  deposit:
    description: Deposit some of your lives in an item form
    usage: /<command>

  omegareset:
    description: Reset a player's life count (OPERATOR-ONLY)
    usage: /<command>
    permission: omegasmp.admin

  omegaset:
    description: Set a player's life count (OPERATOR-ONLY)
    usage: /<command>
    permission: omegasmp.admin

  omegakit:
    description: Kits you out full Omega SMP style!
    usage: /<command>
    permission: omegasmp.admin